import "bootstrap/dist/css/bootstrap.css";

import Head from "next/head";
// import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Archi Web Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/NorthStar-32x32.ico" />
      </Head>

      <main className="body">
        <div>
          <div className="container">
            <h1 className="display-4">
              Archi (ArchiMate) Model HTML Web Portals
            </h1>
            <p>
              Exported from variable Archi model and publish here as web portal views
            </p>
          </div>
        </div>

        <div className="container">
          <div className="row">

            <div className="col-md-4">
              <h2>ArchiSurance</h2>
              <p>ArchiSurance Case Study Modeling (v3.1)</p>
              <a className="btn btn-primary" href="html/ArchiSurance/index.html?view=id-7d7e5cdc6a9043be8add816e1f7dd0db">
                View details »
              </a>
            </div>

            {/* <div className="col-md-4">
              <h2>Other</h2>
              <p>
                text
              </p>
              <Link
                className="btn btn-primary"
                href="AppArch/AppPortfolio"
                alt="Application Portfolio"
              >
                View details »
              </Link>
            </div> */}

          </div>
        </div>
      </main>
    </div>
  );
}
