import "bootstrap/dist/css/bootstrap.css";

import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Archi Web Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/NorthStar-32x32.ico" />
      </Head>

      <main className="body">
        <div>
          <div className="container">
            <h1 className="display-4">
              Archi (ArchiMate) Model HTML Web Portals
            </h1>
            <p>
              Exported from variable Archi model and publish here as web portal views
            </p>
          </div>
        </div>

        <div className="container">
          <div className="row">

            <div className="col-md-4">
              <h2>ArchiSurance</h2>
              <p>ArchiSurance Case Study Modeling (v3.1)</p>
              <a className="btn btn-primary" href="html/ArchiSurance/index.html">
                View details »
              </a>
            </div>

            {/* <div className="col-md-4">
              <h2>VFS Application Architecture</h2>
              <p>
                Variable viewpoints to find suitable VFS applications
                information
              </p>
              <Link
                className="btn btn-primary"
                href="AppArch/VFS_AppPortfolio"
                alt="VFS Application Portfolio"
              >
                View details »
              </Link>
            </div>

            <div className="col-md-4">
              <h2>VFS EA Dashboards</h2>
              <p>
                VFS Enterprise Architecture views from Essential
              </p>
              <a className="btn btn-primary" href="https://segotn17948.vcn.ds.volvo.net/vfs_knowledge_portal/report?XML=reportXML.xml&PMA=essential_baseline_v5_Class83&XSL=common/portal_template.xsl&LABEL=Enterprise%20Architecture%20Portal&cl=en-gb">
                View details »
              </a>
            </div> */}

          </div>
        </div>
      </main>
    </div>
  );
}
